import { useState } from 'react';
import { Drawer } from './ui/Drawer';
import { Badge } from './ui/Badge';
import { Button } from './ui/Button';
import { useQuery } from '@tanstack/react-query';
import api from '../services/api';
import { MOCK_ALERTS } from '../services/mockData';
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { Sparkles, ArrowRight, ShieldBan, CheckCircle2, Flag } from 'lucide-react';
import { useToast } from './ui/Toast';
import { Link } from 'react-router-dom';

interface AlertDetailDrawerProps {
  alertId: string | null;
  isOpen: boolean;
  onClose: () => void;
}

export function AlertDetailDrawer({ alertId, isOpen, onClose }: AlertDetailDrawerProps) {
  const { toast } = useToast();
  const [isUpdating, setIsUpdating] = useState(false);
  const [isGeminiLoading, setIsGeminiLoading] = useState(false);

  const { data: alert, isLoading } = useQuery({
    queryKey: ['alert', alertId],
    queryFn: async () => {
      if (!alertId) return null;
      if (import.meta.env.VITE_MOCK_MODE === 'true' || import.meta.env.DEV) {
        await new Promise(r => setTimeout(r, 400));
        return MOCK_ALERTS.find(a => a.id === alertId) || null;
      }
      const res = await api.get(`/api/v1/alerts/${alertId}`);
      return res.data;
    },
    enabled: !!alertId,
  });

  const handleAction = async (action: string) => {
    setIsUpdating(true);
    try {
      // API call placeholder
      await new Promise(r => setTimeout(r, 600));
      toast({
        title: `Alert ${action} successfully`,
        type: 'success'
      });
      onClose();
    } catch (e) {
      toast({
        title: `Failed to ${action} alert`,
        type: 'error'
      });
    } finally {
      setIsUpdating(false);
    }
  };

  const handleRegenerate = async () => {
    setIsGeminiLoading(true);
    await new Promise(r => setTimeout(r, 1200));
    setIsGeminiLoading(false);
    toast({ title: 'AI Summary regenerated', type: 'info' });
  };

  if (!isOpen) return null;

  // Mock SHAP data derived from factors
  const shapData = alert?.factors.map((f: string, i: number) => ({
    name: f.replace(/_/g, ' '),
    weight: 0.8 - (i * 0.2),
  })) || [];

  return (
    <Drawer 
      isOpen={isOpen} 
      onClose={onClose}
      className="w-full sm:w-[500px] max-w-full"
    >
      {isLoading ? (
        <div className="p-6 space-y-6">
          <div className="animate-pulse h-8 bg-surface-alt rounded w-1/2"></div>
          <div className="animate-pulse h-32 bg-surface-alt rounded w-full"></div>
          <div className="animate-pulse h-32 bg-surface-alt rounded w-full"></div>
        </div>
      ) : alert ? (
        <div className="flex flex-col h-full">
          {/* Header */}
          <div className="p-6 border-b border-border bg-surface-alt/20">
            <div className="flex items-start justify-between mb-2">
              <Badge variant={alert.severity as any} className="uppercase">{alert.severity}</Badge>
              <span className="text-xs text-text-muted">{new Date(alert.timestamp).toLocaleString()}</span>
            </div>
            <h2 className="font-mono text-xl text-text-primary tracking-tight">{alert.id}</h2>
            <div className="mt-4 flex flex-wrap gap-2">
              {alert.factors.map((factor: string) => (
                <Badge key={factor} variant="outline" className="text-[10px]">
                  {factor.replace(/_/g, ' ')}
                </Badge>
              ))}
            </div>
          </div>

          {/* Body */}
          <div className="flex-1 overflow-y-auto p-6 space-y-8">
            
            {/* AI Investigation */}
            <div className="space-y-3">
              <div className="flex items-center justify-between">
                <h3 className="text-sm font-semibold flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-accent" />
                  AI Investigation Summary
                </h3>
                <Button variant="ghost" size="sm" className="h-6 text-xs" onClick={handleRegenerate} isLoading={isGeminiLoading}>
                  Regenerate
                </Button>
              </div>
              <div className="bg-surface-alt/50 border border-border p-4 rounded-card relative">
                <p className="text-sm text-text-secondary leading-relaxed">
                  The entity <span className="font-mono text-text-primary">{alert.entity_id}</span> exhibited abnormal behavior consistent with compromised credentials. Specifically, anomalous authentication attempts were followed by an unusually large transaction request outside typical operating hours.
                </p>
                <div className="mt-3 flex justify-end">
                  <span className="text-[10px] text-text-muted italic">Generated by Gemini · verify before acting</span>
                </div>
              </div>
            </div>

            {/* Attribution Chart */}
            <div className="space-y-3">
              <h3 className="text-sm font-semibold">Risk Attribution (SHAP)</h3>
              <div className="h-48 border border-border rounded-card bg-surface-alt/20 p-4">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={shapData} layout="vertical" margin={{ top: 0, right: 0, bottom: 0, left: 0 }}>
                    <XAxis type="number" hide />
                    <YAxis dataKey="name" type="category" width={140} tick={{ fontSize: 10, fill: 'var(--color-text-secondary)' }} axisLine={false} tickLine={false} />
                    <Tooltip cursor={{ fill: 'var(--color-surface-alt)' }} contentStyle={{ backgroundColor: 'var(--color-bg-surface)', borderColor: 'var(--color-border)', borderRadius: '8px' }} />
                    <Bar dataKey="weight" radius={[0, 4, 4, 0]}>
                      {shapData.map((_entry: any, index: number) => (
                        <Cell key={`cell-${index}`} fill={index === 0 ? 'var(--color-critical)' : 'var(--color-accent)'} />
                      ))}
                    </Bar>
                  </BarChart>
                </ResponsiveContainer>
              </div>
            </div>

            {/* Linked Transaction */}
            {alert.linked_transaction && (
              <div className="space-y-3">
                <h3 className="text-sm font-semibold">Linked Transaction</h3>
                <div className="bg-surface-alt/30 border border-border p-4 rounded-card">
                  <div className="flex justify-between items-center mb-4">
                    <span className="font-mono text-2xl text-text-primary">₹{(alert.linked_transaction.amount).toLocaleString()}</span>
                    <Link to={`/transactions?id=${alert.linked_transaction.id}`} className="text-xs text-accent hover:underline flex items-center gap-1">
                      View details <ArrowRight className="w-3 h-3" />
                    </Link>
                  </div>
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div>
                      <p className="text-text-muted text-xs mb-1">Sender</p>
                      <p className="font-mono text-text-primary">{alert.linked_transaction.sender}</p>
                    </div>
                    <div>
                      <p className="text-text-muted text-xs mb-1">Receiver</p>
                      <p className="font-mono text-text-primary">{alert.linked_transaction.receiver}</p>
                    </div>
                  </div>
                </div>
              </div>
            )}

            {/* Raw JSON Toggle */}
            <details className="group border border-border rounded-card">
              <summary className="px-4 py-3 text-sm font-semibold cursor-pointer select-none text-text-secondary group-hover:text-text-primary transition-colors flex justify-between items-center">
                Raw event data (advanced)
                <span className="text-xs font-mono text-accent bg-accent/10 px-2 py-0.5 rounded">JSON</span>
              </summary>
              <div className="p-4 border-t border-border bg-black/50 overflow-x-auto">
                <pre className="text-xs font-mono text-text-muted">
                  {JSON.stringify(alert.raw, null, 2)}
                </pre>
              </div>
            </details>

          </div>

          {/* Action Footer */}
          <div className="p-4 border-t border-border bg-surface flex flex-col gap-3 shrink-0">
            <div className="flex gap-3">
              <Button 
                variant="destructive" 
                className="flex-1" 
                onClick={() => handleAction('blocked')}
                isLoading={isUpdating}
                disabled={alert.status === 'RESOLVED'}
              >
                <ShieldBan className="w-4 h-4 mr-2" /> Block Transaction
              </Button>
              <Button 
                variant="secondary" 
                className="flex-1"
                onClick={() => handleAction('approved')}
                isLoading={isUpdating}
                disabled={alert.status === 'RESOLVED'}
              >
                <CheckCircle2 className="w-4 h-4 mr-2" /> Approve
              </Button>
            </div>
            <div className="flex gap-3">
              <Button 
                variant="outline" 
                className="flex-1"
                onClick={() => handleAction('escalated')}
                isLoading={isUpdating}
                disabled={alert.status === 'RESOLVED'}
              >
                <Flag className="w-4 h-4 mr-2" /> Escalate
              </Button>
              <Button 
                variant="ghost" 
                className="flex-1 text-xs"
                onClick={() => handleAction('marked as false positive')}
                isLoading={isUpdating}
                disabled={alert.status === 'RESOLVED'}
              >
                Mark False Positive
              </Button>
            </div>
          </div>
        </div>
      ) : (
        <div className="p-6 text-center text-text-muted">Alert not found</div>
      )}
    </Drawer>
  );
}
